### ISSUE TITLE
If combine taskbar buttons is off, drag gets wrong window

### ISSUE THREAD

**Issue by IceLancerSR** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#101]
Hello!
With new update, regular release got Combine taskbar buttons Option.
If i finally turn off combines, drag and drop can no longer find correct app.

it's acting very weird as well. I aim at one app but it doesnt find it and focuses on another and brings it to focus.

**Comment by HerMajestyDrMona** [comment]
Hi. 

Have you tried the older version (2.3.0.0) to see if it makes any difference? I remember the icon selection was fixed after bad windows update broke it, but maybe now they fixed a bug and old version would work better.

Unfortunately, I will most likely not update this program, as there are very few users. The native drag and drop works fine for everyone who did not disable UAC in unsafe way.

**Comment by LiquidatorFX** [comment]
The latest version 2.4 works perfectly on Windows with the latest updates and accurately determines the position of the icon

**Comment by IceLancerSR** [comment]
> The latest version 2.4 works perfectly on Windows with the latest updates and accurately determines the position of the icon

I said if : **combine taskbar buttons is off**
Otherwise, yes it works

Doesnt matter, i ditched win11 and reverted to win10 i cant work with that shit
