### ISSUE TITLE
I'd remapped the arrow keys and couldn't understand why the fix is not working

### ISSUE THREAD

**Issue by dmitrydva** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#17]
Was wondering for a while why it's not working on my laptop, but then I remembered that I had to remap the arrow keys as they are partly broken for now.. Not sure where do I go from here, I guess I'll have to wait a year.

**Comment by HerMajestyDrMona** [comment]
> Not sure where do I go from here, I guess I'll have to wait a year.

No, lol.

What keys you remapped it to? Do you have some keyboard keys assigned to arrows?

**Comment by dmitrydva** [comment]
Yep, one particularly nasty coffee spill led to all this hehe.
Now right ctrl (E0_1D) goes to right arrow (E0_4D)
And right shift (00_36) goes to down arrow (E0_50)

**Comment by HerMajestyDrMona** [comment]
@dmitrydva And did you set the right arrow and the down arrow to some other keys?

**Comment by dmitrydva** [comment]
Maybe I phrased it wrong, but what I meant is when I press right ctrl/right shift, it works as the arrows are pressed.
The right arrow/down arrow aren't set, because the physical buttons don't work regardless.

**Comment by HerMajestyDrMona** [comment]
Ahh... So your "original" right CTRL, and original right SHIFT are not assigned to anything, but pressing them simulates arrow right / down behaviour?

Do you have a possibility to install Visual Studio: https://visualstudio.microsoft.com/ in order to compile the program yourself? I would guide you what to change to assign different keys.

**Comment by HerMajestyDrMona** [comment]
... or I have a better idea,
When you confirm that Right Shift simulates Arrow Down, and Right CTRL simulates Arrow Right, I'll compile the program with these changes for you. When you confirm it works, I'll add a keys remapping possibility with the config file, so in next versions you will be able to remap keys using the program config file. Would that be fine for you?

**Comment by dmitrydva** [comment]
Yes, exactly!

I'll definitely try (tomorrow, as it's 2:20am now where I live), even though I have very little experience in this. Your help would be appreciated!

**Comment by HerMajestyDrMona** [comment]
Ok, let's see. Please quit your current process of Windows11DragAndDropToTaskbarFix.exe, and then start this one: https://we.tl/t-cGfYqT8eBB

Then tell me if it works fine.

**Comment by HerMajestyDrMona** [comment]
Hi @dmitrydva, I released [version 1.8.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-1800----2021-11-02-0700-cet) with possibility to remap keys used by the program.

In your case, please add to the config file:
```
REMAP_VK_DOWN=0xA1
REMAP_VK_RIGHT=0xA3
```

I hope it solves your problem fully :)

**Comment by dmitrydva** [comment]
Yes, it does, thank you very much once again :)
Sorry I couldn't respond earlier!

**Comment by HerMajestyDrMona** [comment]
Thanks for confirmation.
