### ISSUE TITLE
The program is not opened by default.

### ISSUE THREAD

**Issue by ElitePheonix009** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#20]
**The program is not opened by default on Windows 11 on latest version (1.8.0.0). Pls fix this issue ASAP or pls tell how we can open it.**  

> (There's no icon the system tray (in the taskbar) or in the taskbar. Neither I can see the program anywhere. Neither I can drag n drop. Is it uninstalled on its own? I ran the exe as administrator and now it works!)

![image](https://user-images.githubusercontent.com/94096555/141239576-8708ed58-5443-47de-a56f-5f928921671d.png)
![image](https://user-images.githubusercontent.com/94096555/141238916-1dffdc09-9542-4e26-abb5-cc45c6897f64.png)
![image](https://user-images.githubusercontent.com/94096555/141239149-91a5dbc3-f395-4f64-9d0d-b88cb98a4dfa.png)
![image](https://user-images.githubusercontent.com/94096555/141239314-14330abf-a43c-4409-8c8a-0117c710a531.png)
![image](https://user-images.githubusercontent.com/94096555/141239365-1847e98f-1bb3-46b0-8244-db63ff85de18.png)

**Comment by HerMajestyDrMona** [comment]
???

You fix your problem ASAP. Or maybe read the configuration page ASAP.
