### ISSUE TITLE
Always have the console displayed

### ISSUE THREAD

**Issue by texas2607** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#25]
Hi,
In the configuration file I have : :  ShowConsoleWindowOnStartup=0
But when I start Windows, I always have the console displayed

![Capture d’écran 2021-11-19 193504](https://user-images.githubusercontent.com/28494443/142725043-647322dc-eb68-4990-91dd-0a8a1e0447e5.png)

Any idea ?
Thk

**Comment by HerMajestyDrMona** [comment]
Hi. This is strange. Even when there is no configuration file it should not display the console window on startup (default configuration since version 1.8 I think). Could you paste the full content of your config file?

**Comment by texas2607** [comment]
`AutomaticallyRunThisProgramOnStartup=1

ShowConsoleWindowOnStartup=0

PrintDebugInfo=0

UseFixForBugAfterSleepMode=1

ShowTrayIcon=1

UseTheNewBestMethodEver=1

AutoOpenFirstWindowInBestMethodEver=2

HowLongLeftMouseButtonPressedBeforeContinueMilliseconds=750

HowLongKeepMouseOverAppIconBeforeRestoringWindowMilliseconds=200

HowLongSleepBetweenDifferentKeysPressMilliseconds=10

HowLongSleepBetweenTheSameKeysPressMilliseconds=0

HowLongSleepAfterAutoOpenFirstWindowMilliseconds=100

HowLongKeepMouseOverAppIconBeforeAutoOpeningMilliseconds=550

PreviewWindowChangeDetectionMaxMilliseconds=1000

REMAP_VK_LWIN=0x5B
REMAP_VK_MENU=0x12
REMAP_VK_TAB=0x09
REMAP_VK_LCONTROL=0xA2
REMAP_VK_LSHIFT=0xA0
REMAP_VK_LEFT=0x25
REMAP_VK_RIGHT=0x27
REMAP_VK_UP=0x26
REMAP_VK_DOWN=0x28
REMAP_VK_RETURN=0x0D
REMAP_VK_D=0x44
REMAP_VK_T=0x54

DefaultSleepPeriodInTheLoopMilliseconds=100
SleepPeriodWhenLeftMouseButtonIsPressedInTheLoopMilliseconds=25
SleepPeriodWhenMouseIsOnAppIconInTheLoopMilliseconds=10
DefaultTaskbarIconWidth=44
DefaultTaskbarIconHeight=48
DefaultShowDesktopButtonWidth=20
DefaultSingleWindowPreviewThumbnailWidth=250
DefaultSingleWindowPreviewThumbnailHeight=250

ConfigFileChangeTimeMonitorAllowed=1

UseAlternativeTrayIcon=0`

**Comment by HerMajestyDrMona** [comment]
I think I know what the problem was. The description of variables:
`//Should the program print the debug information?
//1 = YES. If ShowConsoleWindowOnStartup=1 the program will print a lot of messages about the actions done.`

Maybe it updated it based on this line. Theoretically it should ignore lines with `//` in front, so it needs to be checked :)

**Comment by HerMajestyDrMona** [comment]
Hi again. I tested the config file that you pasted, and it still wasn't displaying the console window on start.
So the `//` detection works fine. That must been something strange and rare.

For the future, I would recommend to follow the [CONFIGURATION](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md)

> You don't need to add all variables to your configuration file. Please only add the ones you need. The program will use the same default values as present after `Variable=Value` listed below.
