### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by skri11-2k** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#26]
I configured the txt file for it to start automatically but neither does it create the registry key nor does it automatically run on startup.

**Comment by skri11-2k** [comment]
run as administrator solves it

**Comment by HerMajestyDrMona** [comment]
When you ran it as administrator 1 time, can you confirm that the next time you started computer it started normally and was not needed to run as administrator manually? The program works fine for you when it's running normally, right?

**Comment by skri11-2k** [comment]
it runs perfectly and it doesn't need to run as administrator each time but has a popup on every startup, 'always ask to run this file' once unticked it automates the process.

**Comment by HerMajestyDrMona** [comment]
Just to make sure I understood everything correctly. You had manually ticked option "Run this program as administrator" in Properties -> Compatibility tab? And now you unticked it and it doesn't show any popup on program start after computer restart?

**Comment by HerMajestyDrMona** [comment]
@skri11-2k I think I now know what was the problem. When programs are manually set in the compatibility tab to start as administrator - they won't start after computer restart. It's some security thing from Windows.

In [ver. 2.2.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2200----2022-01-10-1400-cet) I have added a new option that allows you to run the program as administrator on startup. This option will work even after the normal program autostart. It's only useful if you're often dragging files from other programs that are running as administrator.
