### ISSUE TITLE
Windows Defender Detection (Trojan:Win32/Wacatac.B!ml)

### ISSUE THREAD

**Issue by UnnieChaeng** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#27]
Windows defender detected it as a virus. 
![image](https://user-images.githubusercontent.com/73013338/142756222-db2580d3-1ebf-4b58-a4e6-ad9707b66146.png)

**Comment by HerMajestyDrMona** [comment]
Ummmm... Again?
Related to: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/10

Which version are you using at the moment? I scanned ver. 1.9.1.0 and it didn't show anything.

**Comment by HerMajestyDrMona** [comment]
No answer from the author, so the issue is being closed as I can not reproduce it.
