### ISSUE TITLE
installer file is corrupted!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ashmit001** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#29]
the .exe installer is corrupted
the edge browser is showing that it is malicious
but still i run it anyway
but it is showing that the file  is corrupted

**Comment by HerMajestyDrMona** [comment]
There is no installer. The program is portable.

Did you try re-downloading it? Are you sure that the Edge browser claims it's malicious or **POTENTIALLY** malicious?

**Comment by HerMajestyDrMona** [comment]
No further feedback from the author. Closing this issue for now.
