### ISSUE TITLE
It doesn't work for me..

### ISSUE THREAD

**Issue by ilkersays** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#44]
It doesn't work for me.. i also configured to.. but doesn't show any drag and drop thing.

edit : it worked with version 1.8.00 but any other further versions doesn't work.

**Comment by HerMajestyDrMona** [comment]
Did you install redistributables? https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#install-microsoft-visual-c-2015-2022-redistributable-x64 ?
I remember ver. 1.9 was compiled as non-static, so that would signal that there's some problem with missing runtime libraries on your PC, but you should see an error regarding it.

Please try to instlll these redists and tell if it works.

**Comment by HerMajestyDrMona** [comment]
Also, can you see the tray icon in newer verions?

**Comment by ilkersays** [comment]
firstly, mvc2015-22 was already installed on my computer. 
also, i didn't see any error regarding it.
yeah i can see tray icon in newer versions.

**Comment by HerMajestyDrMona** [comment]
What did you mean by: "doesn't show any drag and drop thing"?

So just to summary, the program starts normally, the tray icon is shown, but the drag and drop gesture doesn't restore windows under icons? Are you sure the same problem persists already on version 1.9?

**Comment by ilkersays** [comment]
- 2.0 and 2.1 didn't work ( although the icon is showing )
- 1.9 and 1.8 works fine.
- "doesn't show any drag and drop thing" means : i can see tray icon and software settings but can't drag and drop.

**Comment by HerMajestyDrMona** [comment]
Ok, it makes more sense now as ver. 2.0 had more changes.

Did you try this? https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#limitations

`DetectKnownPixelColorsToPreventAccidentalEvents=0`

I would guess that you're using some custom theme that displays the error icon differently. Please insert that configuration line and test if it works.

**Comment by ilkersays** [comment]
I will try this thank you for your help!

**Comment by HerMajestyDrMona** [comment]
@ilkersays Since you closed this issue, can you please confirm that it was the problem?
