### ISSUE TITLE
Kaspersky Security Cloud detects as a false positive? 

### ISSUE THREAD

**Issue by TheGhostie21** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#5]
![avpui_pVeeJ45cgy](https://user-images.githubusercontent.com/62975008/137788199-6be0fc7c-de1f-40a5-b86c-872580eb7d4b.png)

**Comment by TheGhostie21** [comment]
Oh, I excluded just the file itself (in the Downloads folder); I didn't show it because it had my name for users.

**Comment by HerMajestyDrMona** [comment]
Ah, i thoughr you added a wilcard exclusion for the whole Users folder :)

**Comment by HerMajestyDrMona** [comment]
@TheGhostie21, could you please check if version 1.4.0 still has false positives problem?
