### ISSUE TITLE
W11DADTTF shows up in taskbar when dragging on some application

### ISSUE THREAD

**Issue by andrescirulo** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#51]
Sometimes, when i hold down the mouse button on some application, the W11DADTTF icon shows briefly on the taskbar

**Comment by HerMajestyDrMona** [comment]
Please read my posts in: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/45

It's a fix for the taskbar size bug, an expected feature.
