### ISSUE TITLE
[Feature request] Disable tab support

### ISSUE THREAD

**Issue by DanRotaru** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#53]
Add possibility to disable tab support (this white border on each taskbar icon)
![image](https://user-images.githubusercontent.com/7759507/150231632-498b4081-03f4-4189-85ca-3d535c269b02.png)

**Comment by HerMajestyDrMona** [comment]
This is impossible. The white frame appears when the Win+T hotkey is being simulated. It's unintentional, but it's Windows controlled.
