### ISSUE TITLE
Please create static build

### ISSUE THREAD

**Issue by ALIENQuake** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#57]
Hi, Please create static build so Microsoft Visual C++ 2015-2022 Redistributable x64 si not required.

**Comment by ALIENQuake** [comment]
A separate build is a good idea, especially if you automate compiling process using GitHub Actions CI/CD. I know that it's an uncommon thing but this app will be used by many people after switching from Windows 10 to 11 so having it 'portable' out-of-the-box is a huge benefit for automatic Windows image deployment/unattended installation etc.

**Comment by HerMajestyDrMona** [comment]
Hi again.

I added the static build in ver. [ver. 2.3.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2300----2022-02-15-1730-cet).

Sorry that it took longer than intended. I had / have some neurological issues after Covid or the vaccine, or both of them at the same time, so I was not motivated to focus on it.
