### ISSUE TITLE
app doesn't work in all of a sudden

### ISSUE THREAD

**Issue by ZinerX** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#65]
app is opened but not working, tried running with admin permission and restarting but not sure why.
i changed quite a lot of windows registry settings recently i dont know if that affected the app but im not sure which one affected it.

**Comment by HerMajestyDrMona** [comment]
Try this: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#should-the-program-check-colors-of-pixels-in-order-to-prevent-the-accidental-events-when-no-item-is-being-dragged-it-solves-issues-1-and-2

**Comment by HerMajestyDrMona** [comment]
No further information from the author, so closing this issue.
