### ISSUE TITLE
 Not Working on my Windows 11 - Windows11DragAndDropToTaskbarFix

### ISSUE THREAD

**Issue by SudiptoKP** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#67]
Windows11DragAndDropToTaskbarFix is installed showing the icon in tray but the Drag and Drop is now working. Please get a solution.

**Comment by HerMajestyDrMona** [comment]
Have you maybe tried this configuration option?
https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#should-the-program-check-colors-of-pixels-in-order-to-prevent-the-accidental-events-when-no-item-is-being-dragged-it-solves-issues-1-and-28

**Comment by HerMajestyDrMona** [comment]
No further information from the author, so closing this issue.
