### ISSUE TITLE
do i have to run the program everytime windows starts?

### ISSUE THREAD

**Issue by exhaka** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#68]

**Comment by HerMajestyDrMona** [comment]
You can read the configuration page to make it autostart: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#should-the-program-run-automatically-on-system-startup

**Comment by HerMajestyDrMona** [comment]
No further information from the author, so closing this issue.
