### ISSUE TITLE
Some instances of explorer.exe crashing when I try to drag and drop a video file onto the taskbar

### ISSUE THREAD

**Issue by shantanub08** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#69]
I could manage to drag and drop all other types of files except video ones. Specifically, .mp4. Is it just me or others can drag and drop video files without any crashing? I said some instances because the folder from which I'm draging the video doesn't crash but the taskbar crashes

Edit: I realized it's worth mentioning that I'm using Stardock's Start11 which may or may not alter the behaviour of Windows11DragAndDropToTaskbarFix

**Comment by HerMajestyDrMona** [comment]
I can drag-and-drop the .mp4 files correctly.

What default video player do you use?

Could you try to change the default video player for .mp4 files and test if it works?

**Comment by shantanub08** [comment]
> Could you try to change the default video player for .mp4 files and test if it works?

Yes. Changing it to Windows 11's new Media Player (which supports both audio and video playback) fixed it

**Comment by HerMajestyDrMona** [comment]
> > Could you try to change the default video player for .mp4 files and test if it works?
> 
> Yes. Changing it to Windows 11's new Media Player (which supports both audio and video playback) fixed it

And which video player was it before?

**Comment by shantanub08** [comment]
> And which video player was it before?

VLC

**Comment by HerMajestyDrMona** [comment]
> > And which video player was it before?
> 
> VLC

Hmm, not cool. It's quite a popular player :(
