### ISSUE TITLE
Not working when using Windows Terminal Preview

### ISSUE THREAD

**Issue by likkai** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#7]
The executable file only runs when the cmd close automatically but when the default console is switched to windows terminal preview, the windows terminal will not close and stuck at the 'Debug output...' screen, rendering the executable file unusable. This is only a minor issue as this can be fixed by simply opening with cmd. 
![image](https://user-images.githubusercontent.com/76016664/138220237-3fb63d93-18fb-4523-a651-d8e9c3f60a8e.png)

**Comment by HerMajestyDrMona** [comment]
Could you please test how it works with the newest version? 1.0 is quite outdated as it was the first release.
