### ISSUE TITLE
emails in mozilla thunderbird

### ISSUE THREAD

**Issue by enascim71** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#73]
very good, unfortunately drag and drop of attached files of emails doesnt work when making a new email on mozilla thunderbird

**Comment by HerMajestyDrMona** [comment]
Did it work on Windows 10 this way? Have you tried to re-launch the fix as administrator?

**Comment by enascim71** [comment]
> Did it work on Windows 10 this way? Have you tried to re-launch the fix as administrator?

yes, in windows 10 it was possible to move attached files from emails in the inbox, to new emails. yes i'm using the fix as administrator

**Comment by enascim71** [comment]
wait, i just made it... got yo wait a moment to the new email window popup from the task bar

thanks!

**Comment by HerMajestyDrMona** [comment]
@enascim71 You can try to tweak the delay values in the configuration to speed it up. For example: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#delay-in-milliseconds-before-opening-the-first-window-under-the-icon-only-if-autoopenfirstwindowinbestmethodever-is-2-or-1

It's hard to tell which delays are the best. I was trying to pick the optimal values that work for everyone, even people who are using slow processors, but after all everyone has their own preferences.
