### ISSUE TITLE
You cant drop Downloaded files from chrome to a folder

### ISSUE THREAD

**Issue by fluffy29922** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#8]
![image](https://user-images.githubusercontent.com/74750370/138580349-cfaf63e5-004d-4fa0-b1f9-6a2dc1123c5e.png)

**Comment by supermj767** [comment]
I was having this same issue and found a fix. If anyone else is wondering how to fix it, just disable "automatically hide the taskbar" in the taskbar settings.

**Comment by HerMajestyDrMona** [comment]
@supermj767 Interesting, thanks for sharing the solution.

I think it's not that big issue though, since the fix is not longer needed in Windows 11 22H2.
