### ISSUE TITLE
hide the forbidden mouse icon

### ISSUE THREAD

**Issue by itismoradi** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#80]
when i want to drag and drop a image to a window, mouse icon will be forbidden icon.
can you solve it?

![image](https://user-images.githubusercontent.com/75095946/178138317-4aa64247-9498-4034-b66c-7f028e13cad1.png)

**Comment by HerMajestyDrMona** [comment]
This icon can not be removed (without affecting the system registry or other modifications which should not be done by this portable program).

Additionally, this icon is used by the program to detect if the item is currently being dragged. It was explained for example here:
https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/35#issuecomment-986100443

And in the change log: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2000----2021-11-28-1530-cet

> Added DetectKnownPixelColorsToPreventAccidentalEvents=1 configuration option (enabled by default) which prevents the accidental events when no item is being dragged. It fixes issues https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/1 and https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/28
The function checks a few colors of pixels above the mouse pointer on the taskbar. It detects the "incorrect" sign that is shown when something is being dragged over Windows 11 taskbar. When the sign is not detected, the program will not restore the window from the icon. It's useful when selecting files by the drag gesture, or when selecting text / rows in Word / Excel, and probably many other programs.
