### ISSUE TITLE
this app is still relevant.

### ISSUE THREAD

**Issue by volkan-akkus-tr** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#89]
I have just updated Win 11 and there is nothing new about the subject.

As Dave explained at 10/7/2022 6:47:59 PM...

I am Dave, I will help you with this.
Windows11 does not yet support drag and drop onto the Taskbar, that functionality was meant to be in the 22h2 update, but a few of those features were not ready in time for the update, there is a large update to Windows 11 this month and that new functionality should be in that update. 

https://answers.microsoft.com/en-us/windows/forum/all/windows-11-22h222621608-drag-drop-not-working/102f3135-60f0-4920-8df9-e7af3fe51d17

**Comment by HerMajestyDrMona** [comment]
That's strange... I was using it for a few months in 22H2, but maybe I got it enabled because I was in BETA channel.

**Comment by ElitePheonix2009** [comment]
Drag and Drop to taskbar has been added to windows 11 22h2.

**Comment by HerMajestyDrMona** [comment]
> 

He posted a source of this information.

**Comment by volkan-akkus-tr** [comment]
![22H2](https://user-images.githubusercontent.com/115474856/200077558-3e2229b8-9eb7-4e5a-af4e-3bf6e0157752.png)

**Comment by ElitePheonix2009** [comment]
I cannot test it as I don't have windows 11 but many news articles and YouTube videos are saying that the feature has been added to windows 11 22h2.

**Comment by HerMajestyDrMona** [comment]
@volkan-akkus-tr From what I remember, the native drag and drop was never opening closed apps. This is an "unique" feature of this program:
[Should the program open pinned apps, even when there is no active window? It solves discussion 37.](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#should-the-program-open-pinned-apps-even-when-there-is-no-active-window-it-solves-discussion-37)

**Comment by ElitePheonix2009** [comment]
> @volkan-akkus-tr From what I remember, the native drag and drop was never opening closed apps. This is an "unique" feature of this program: [Should the program open pinned apps, even when there is no active window? It solves discussion 37.](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#should-the-program-open-pinned-apps-even-when-there-is-no-active-window-it-solves-discussion-37)

Yes, It doesn't support opening closed tabs. 
> Seems like Microsoft is enabling "features" randomly to users... for testing purposes? Just another weird policy...

They enable features randomly to users for testing purposes.

**Comment by volkan-akkus-tr** [comment]
it is ok.  
thank you for your kind attention.
I just wanted to let you know.

Best regards,
