### ISSUE TITLE
Fatal error "0x0000idiоt1". 

### ISSUE THREAD

**Issue by Shanti099** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#96]
Would you please replace variable "i'm an idiоt" back to "Putin".
Thanks :)

**Comment by Shanti099** [comment]
Thanks, I compiled in Visual Studio with the "Putin" variable, now it works like a charm :) 

But seriously, I lived all my life in Russia, and yes, there are a lot of bad people and events in Russia just like everywhere else in the world, and the president himself is not a perfect person like all of us, but in more than 20 years, I can feel how and what he says and does, and despite everything you are told and shown on TV, he is a good person, who often has to make tough decisions. 

And as someone who has lived in Russia for so many years, i believe, I am the best judge, for the president of my country. But not some ICC out there, who got his orders over the phone or via messenger from another continent.

I Just got emotionally hurt, so to speak, that a man who has put his whole life in the service of his country is called a criminal. And I apologize for using an offensive word. 

Thank you for your helpful application :)

Please feel free, so to speak, to delete my comment.

**Comment by HerMajestyDrMona** [comment]
I'm not sure why your comment should be deleted. It's the best evidence that not only Putin is responsible for all these crimes, but also a huge part of the Russian nation who supports this terrorism.

Your "good president" who is in power for "more than 20 year" (in democratic countries it's called a dictator) has already killed over 200 000 of your friends, neighbors and other Russians who didn't necessarily want to die in this nonsense war.

The discussion about it doesn't make the further sense as you are clearly brainwashed by the propaganda, or you are simply posting such content on request. Everybody with the basic access to information / Internet already knows who is the aggressor in this conflict.

Please also answer to yourself why your beloved country with so many natural resources, making billions of dollars (or trillions of rubles) manage to have streets full of trash and dingy buildings in most of smaller towns. Please answer to yourself why so many Russians living in villages lack such basic things as toilets/bathrooms at home. Is this a symbol of a country well-cared by your beloved "president"? Where did all these money go, if even your military power was built on a huge lie and is incapable of doing anything else than sacrificing people? What does your beloved leader need more territories for if he is incapable of taking care of people living on the existing ones?
