### ISSUE TITLE
Windows11DragAndDropToTaskbarFix not working anymore

### ISSUE THREAD

**Issue by FPM01GH** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#97]
Hello,
Just a quick word to let you know the Drag&Drop doesn't work anymore on any of my PCs (NUC12 / HP X360) with Win 11 (22H2 with latest kb / French) and same with your 1.9, 2.1 and 2.3 releases with all Visual C++ updates. Even the D&D on the bottom right corner doesn't work anymore. Thanks in advance for your help !

**Comment by HerMajestyDrMona** [comment]
Hi. The drag and drop support was added natively to Windows 11 22H2, so you shouldn't even need to use this program.

Maybe there's some useful information in this thread? https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/discussions/94#discussioncomment-5436281

**Comment by FPM01GH** [comment]
Hi,

Thanks for your quick reply !

I confirm D&D natively not working on my 22H2 (w11 French) but I restore DrMona to get it working again.

Cheers.

Fr.

 

De : Dr.MonaLisa ***@***.***> 
Envoyé : lundi 3 juillet 2023 21:52
À : HerMajestyDrMona/Windows11DragAndDropToTaskbarFix ***@***.***>
Cc : FPM01GH ***@***.***>; Author ***@***.***>
Objet : Re: [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix] Windows11DragAndDropToTaskbarFix not working anymore (Issue #97)

 

Hi. The drag and drop support was added natively to Windows 11 22H2, so you shouldn't even need to use this program.

Maybe there's some useful information in this thread? #94 (reply in thread) <https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/discussions/94#discussioncomment-5436281>
