### ISSUE TITLE
I can’t drag the dragged file to the desired icon Windows11 OS Build 22621.2361

### ISSUE THREAD

**Issue by LiquidatorFX** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#99]
When I run Windows11DragAndDropToTaskbarFix in the new Windows, I can’t get the dragged file to the desired icon, I drag it, another program window opens with a shift of 5-6 icons to the right relative to the place where I drag

**Comment by LiquidatorFX** [comment]
https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/assets/88746476/432ef8fc-12e6-4759-bb04-c9b94c8b93ad

**Comment by LiquidatorFX** [comment]
How to solve such a problem?

https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/assets/88746476/723c0840-d00f-45e3-9948-ea2b1bb986db

**Comment by LiquidatorFX** [comment]
How to solve such a problem?

https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/assets/88746476/44eb2ed7-ed38-4a24-81fd-f6b4f7f0b168

**Comment by HerMajestyDrMona** [comment]
But why would you need to use this program, created for the first version of Windows 11? The drag and drop support was restored in Windows 11 natively.

I think it's better to focus on why the native drag and drop is not working for you. Maybe you uses some "tweaker" programs that changed registry keys?

**Comment by LiquidatorFX** [comment]
> But why would you need to use this program, created for the first version of Windows 11? The drag and drop support was restored in Windows 11 natively.
> 
> I think it's better to focus on why the native drag and drop is not working for you. Maybe you uses some "tweaker" programs that changed registry keys?

I don't use external tweaks and work from the built-in administrator account on an official purchased Windows (I just disabled UAC and Windows Defender). However, the built-in drag-and-drop function did not work initially when I installed the OS in March (at that time the latest build from the Microsoft website), and it still does not work after a bunch of new updates to this day. And reinstalling the OS again just to test this damn function is very time-consuming, I don’t have that time, since setting up working programs will take several days!
    Currently, in the most recent OS build, when you disable your wonderful program, the built-in drag and drop does not work! Only your program saves the situation and I can use drag and drop similar to what was in previous Windows 7, 8, 10. But now in OS Build 22621.2361 an unpleasant offset has appeared ;(
     I think with the crooked hands from Microsoft it’s too early for you to stop supporting your wonderful program ;) I’m still waiting for updates ;)

    If you know how to correctly enable built-in drag and drop and it will work like on Windows 10 (I haven’t found a working method anywhere), can you tell me how?

**Comment by LiquidatorFX** [comment]
I use these settings

//Should the program run automatically on system startup? 1 = true, 0 = false.
AutomaticallyRunThisProgramOnStartup=1
StartThisProgramAsAdministrator=1
UseAlternativeTrayIcon=1
AutoOpenFirstWindowInBestMethodEver=0
HowLongKeepMouseOverAppIconBeforeRestoringWindowMilliseconds=50

//For more configuration options, please visit: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md

**Comment by LiquidatorFX** [comment]
https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/assets/88746476/46e8682f-91c4-4e85-8d99-4fbcad98da71

**Comment by LiquidatorFX** [comment]
So I’m really looking forward to an update from you - this is the only salvation. Microsoft are crooked morons who broke something that worked for many years!

**Comment by HerMajestyDrMona** [comment]
What if you re-enable UAC in defender settings? Does the native drag and drop start working then?

I don't really have possibilities to update this program, as the native drag and drop works for me on all machines, so it's impossible to see if the program is working or its the native function that works.

**Comment by LiquidatorFX** [comment]
> What if you re-enable UAC in defender settings? Does the native drag and drop start working then?
> 
> I don't really have possibilities to update this program, as the native drag and drop works for me on all machines, so it's impossible to see if the program is working or its the native function that works.

in the video I tried to enable UAC, but it does not help :( Perhaps I need to create a new account, and not use the built-in administrator, but again this is nonsense when OS dictates to me that I need to enable UAC, use another account.... it's all crap

**Comment by LiquidatorFX** [comment]
In short the situation is like this:
1) I just created a new account and in the newly created account the built-in drag and drop works
2) I went back to my main account - the built-in administrator account - and unfortunately the built-in drag and drop does not work on it, either with UAC enabled or disabled.

    Thus, I discovered that it is not possible to enable the built-in drag-and-drop function in the built-in administrator account (and it is my main account), so your software remains as relevant as ever! Therefore, if possible, please check your built-in administrator account - does the built-in drag and drop work for you? If not, then we are waiting for an update, since Microsoft does not seem to have completely closed the issue.

**Comment by HerMajestyDrMona** [comment]
Let's only use a single thread: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/98
